#!/bin/bash
#SBATCH --job-name=reid
#SBATCH --ntasks=1
#SBATCH --mem=30gb
#SBATCH --time=180:00:00
#SBATCH --partition=vision
#SBATCH --gres=gpu:1080ti:1
#SBATCH --output=./out/mmdet_%j.out
#SBATCH --error=./out/mmdet_%j.err

pwd; hostname; nvidia-smi; date

singularity exec ../../images/torch.simg jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --port=7788 --no-browser

date
