#!/bin/bash
#SBATCH --job-name=reid
#SBATCH --ntasks=1
#SBATCH --mem=30gb
#SBATCH --time=180:00:00
#SBATCH --partition=vision
#SBATCH --gres=gpu:1080ti:1
#SBATCH --output=./out/mmdet_%j.out
#SBATCH --error=./out/mmdet_%j.err

pwd; hostname; nvidia-smi; date

singularity exec ../../images/torch.simg python3 train.py --name idt_15_prcp_20 --source_path ../../datasets/JTA_parsed/ --target_path ../../datasets/DukeMTMC/ \
	--lambda_cls 1.5 --lambda_idt 15 --lambda_prcp 20 \
	--sched --phase 10000 --sample_iters 500 --save_iters 10000 --path_vgg_weights vgg_weights --prefix_vgg_weights imagenet #--ckpt_name ./checkpoints/first_attempt/000010_8.model

date
