#!/bin/bash
#SBATCH --job-name=reid
#SBATCH --ntasks=1
#SBATCH --mem=30gb
#SBATCH --time=180:00:00
#SBATCH --partition=vision
#SBATCH --gres=gpu:1080ti:1
#SBATCH --output=./out/mmdet_%j.out
#SBATCH --error=./out/mmdet_%j.err

pwd; hostname; nvidia-smi; date

singularity exec ../../images/torch.simg python3 train.py --name Market1501_jta_2_duke_resnet9__jta_2_duke_resnet9 --nepochs 100 --warmup_epoch 6 --start_step_lr 40 --dataroot ../../datasets/Market-1501 --dataroot ../../datasets/jta_2_duke_resnet9 --gpu_id 0 --save_suffix pre --log_file pre_log
singularity exec ../../images/torch.simg python3 test.py --name Market1501_jta_2_duke_resnet9__jta_2_duke_resnet9 --dataroot ../../datasets/DukeMTMC/ --gpu_id 0 --save_suffix pre --initial_suffix pre
singularity exec ../../images/torch.simg python3 train.py --name Market1501_jta_2_duke_resnet9__jta_2_duke_resnet9 --nepochs 40 --lr 0.0001 --start_step_lr 20 --dataroot ../../datasets/jta_2_duke_resnet9 --gpu_id 0 --only_backbone --initial_weights Market1501_jta_2_duke_resnet9__jta_2_duke_resnet9 --initial_suffix pre --pretrain_classifiers_epochs 5 --log_file latest_log
singularity exec ../../images/torch.simg python3 test.py --name Market1501_jta_2_duke_resnet9__jta_2_duke_resnet9 --dataroot ../../datasets/DukeMTMC/ --gpu_id 0

date
