#!/bin/bash
#SBATCH --job-name=reid
#SBATCH --ntasks=1
#SBATCH --mem=30gb
#SBATCH --time=180:00:00
#SBATCH --partition=vision
#SBATCH --gres=gpu:1080ti:1
#SBATCH --output=./out/mmdet_%j.out
#SBATCH --error=./out/mmdet_%j.err

pwd; hostname; nvidia-smi; date
singularity exec ../../images/torch.simg python3 train.py --name DukeMTMC__jta_2_duke_resnet9_v2 --nepochs 160 --warmup_epoch 6 --start_step_lr 40 --checkpoint_every 161 --dataroot ../../datasets/DukeMTMC/ --dataroot ../../datasets/jta_2_duke_resnet9/ --gpu_id 0
singularity exec ../../images/torch.simg python3 test.py --name DukeMTMC__jta_2_duke_resnet9_v2 --dataroot ../../datasets/DukeMTMC/ --gpu_id 0
date
